version: '3.7'

services:
  api:
    image: flask_api
    build:
      context: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  modelsvc:
    image: model
    build:
      context: ./model
    ports:
      - 5000:5000
